export const theme = {
  colors: {
    background: "#2e3440",
    accent: "#cba6f7",
    activity: "#8fbcbb",
    success: "#a3be8c",
    error: "#bf616a",
    text: "#eceff4",
    secondary: "#d8dee9",
    muted: "#d8dee9", // Nord subtext equivalent for muted text
    border: "#4c566a",
    panel: "#2e3440",
    userPanel: "#2e3440",
    assistantPanel: "#2e3440",
    inputPanel: "#2e3440",
    toolPanel: "#2e3440",
    pendingPanel: "#2e3440",
    assistantBorder: "#81a1c1",
  },
  glyphs: {
    active: "›",
    inactive: " ",
    user: "›",
    assistant: "·",
    output: "│",
    success: "✔",
    error: "✖",
    pending: "…",
    separator: " · ",
    section: "─",
    userLabel: "you",
    assistantLabel: "excelsior",
    inputLabel: "compose",
  },
  spacing: {
    indent: 2,
    toolIndent: 3,
  },
} as const;
