export interface ThemeTokens {
  accent: string;
  activity: string;
  success: string;
  error: string;
  text: string;
  secondary: string;
  muted: string;
  border: string;
  assistantBorder: string;
  assistantText: string;
  assistantEmphasis: string;
  assistantBullet: string;
  highlight: string;
  highlightSecondary: string;
  toolCommand: string;
  toolArgs: string;
  highlightBrand: string;
  highlightHeading: string;
  highlightEmphasis: string;
  highlightInline: string;
  highlightLink: string;
  highlightPriority: string;
  highlightSelected: string;
  highlightAction: string;
  diffRemovedText: string;
  diffAddedText: string;
  diffContextText: string;
  diffGutter: string;
  diffBorder: string;
  modeHintKey: string;
  modeHintPlan: string;
  modeHintAct: string;
  syntaxKeyword: string;
  syntaxBuiltIn: string;
  syntaxType: string;
  syntaxLiteral: string;
  syntaxNumber: string;
  syntaxRegexp: string;
  syntaxString: string;
  syntaxSubst: string;
  syntaxSymbol: string;
  syntaxClass: string;
  syntaxFunction: string;
  syntaxTitle: string;
  syntaxParams: string;
  syntaxComment: string;
  syntaxTag: string;
  syntaxAttr: string;
  syntaxVariable: string;
}

const EXCELSIOR: ThemeTokens = {
  accent: "#f5c026",
  activity: "#f5c026",
  success: "#7ece78",
  error: "#f07171",
  text: "#ece7d5",
  secondary: "#c8c2ae",
  muted: "#86806d",
  border: "#3e382b",
  assistantBorder: "#5a523f",
  assistantText: "#ece7d5",
  assistantEmphasis: "#f5c026",
  assistantBullet: "#f5c026",
  highlight: "#f5c026",
  highlightSecondary: "#cf9d22",
  toolCommand: "#f5c026",
  toolArgs: "#9e9783",
  highlightBrand: "#f5c026",
  highlightHeading: "#ffd644",
  highlightEmphasis: "#cf9d22",
  highlightInline: "#fff6d6",
  highlightLink: "#f5c026",
  highlightPriority: "#ffd644",
  highlightSelected: "#ffd644",
  highlightAction: "#f5c026",
  diffRemovedText: "#f07171",
  diffAddedText: "#7ece78",
  diffContextText: "#c8c2ae",
  diffGutter: "#706b5b",
  diffBorder: "#3e382b",
  modeHintKey: "#cf9d22",
  modeHintPlan: "#7ece78",
  modeHintAct: "#f5c026",
  syntaxKeyword: "#f5c026",
  syntaxBuiltIn: "#9dc490",
  syntaxType: "#88cfc0",
  syntaxLiteral: "#ffd644",
  syntaxNumber: "#f5a832",
  syntaxRegexp: "#f07c65",
  syntaxString: "#c2d968",
  syntaxSubst: "#a4ac98",
  syntaxSymbol: "#f5c026",
  syntaxClass: "#88cfc0",
  syntaxFunction: "#9dc490",
  syntaxTitle: "#ffd644",
  syntaxParams: "#a4ac98",
  syntaxComment: "#6d6857",
  syntaxTag: "#f07c65",
  syntaxAttr: "#f5c026",
  syntaxVariable: "#eae5d1",
};

export const THEMES: Record<string, ThemeTokens> = {
  excelsior: EXCELSIOR,
};

export const DEFAULT_THEME_NAME = "excelsior";
