export interface ThemeTokens {
  background: string;
  accent: string;
  activity: string;
  success: string;
  error: string;
  text: string;
  secondary: string;
  muted: string;
  border: string;
  panel: string;
  userPanel: string;
  assistantPanel: string;
  inputPanel: string;
  toolPanel: string;
  pendingPanel: string;
  assistantBorder: string;
  assistantText: string;
  assistantEmphasis: string;
  assistantBullet: string;
  highlight: string;
  highlightSecondary: string;
  toolCommand: string;
  toolArgs: string;
  highlightBrand: string;
  highlightHeading: string;
  highlightEmphasis: string;
  highlightInline: string;
  highlightLink: string;
  highlightPriority: string;
  highlightSelected: string;
  highlightAction: string;
  diffRemovedBackground: string;
  diffAddedBackground: string;
  diffRemovedText: string;
  diffAddedText: string;
  diffContextText: string;
  diffGutter: string;
  diffHeaderBackground: string;
  diffBorder: string;
  modeHintKeyBg: string;
  modeHintKey: string;
  modeHintPlanBg: string;
  modeHintPlan: string;
  modeHintActBg: string;
  modeHintAct: string;
  syntaxKeyword: string;
  syntaxBuiltIn: string;
  syntaxType: string;
  syntaxLiteral: string;
  syntaxNumber: string;
  syntaxRegexp: string;
  syntaxString: string;
  syntaxSubst: string;
  syntaxSymbol: string;
  syntaxClass: string;
  syntaxFunction: string;
  syntaxTitle: string;
  syntaxParams: string;
  syntaxComment: string;
  syntaxTag: string;
  syntaxAttr: string;
  syntaxVariable: string;
}

const EXCELSIOR: ThemeTokens = {
  background: "#141414",
  accent: "#c6c6c6",
  activity: "#c6c6c6",
  success: "#b5b5b5",
  error: "#a6a6a6",
  text: "#c6c6c6",
  secondary: "#c6c6c6",
  muted: "#919191",
  border: "#4e4e4e",
  panel: "#202020",
  userPanel: "#202020",
  assistantPanel: "#202020",
  inputPanel: "#202020",
  toolPanel: "#202020",
  pendingPanel: "#202020",
  assistantBorder: "#919191",
  assistantText: "#c6c6c6",
  assistantEmphasis: "#8d8072",
  assistantBullet: "#a6a6a6",
  highlight: "#a89468",
  highlightSecondary: "#8d8072",
  toolCommand: "#8a8a8a",
  toolArgs: "#8a8a8a",
  highlightBrand: "#a89468",
  highlightHeading: "#a89468",
  highlightEmphasis: "#a89468",
  highlightInline: "#afafaf",
  highlightLink: "#a89468",
  highlightPriority: "#9a816b",
  highlightSelected: "#b8a078",
  highlightAction: "#a89468",
  diffRemovedBackground: "#3a151b",
  diffAddedBackground: "#0d3513",
  diffRemovedText: "#a67b7c",
  diffAddedText: "#6d8f73",
  diffContextText: "#c6c6c6",
  diffGutter: "#868f99",
  diffHeaderBackground: "#1e2530",
  diffBorder: "#444c55",
  modeHintKeyBg: "#2a241c",
  modeHintKey: "#8a8274",
  modeHintPlanBg: "#22302c",
  modeHintPlan: "#729382",
  modeHintActBg: "#302b22",
  modeHintAct: "#8d8072",
  syntaxKeyword: "#c4a7e7",
  syntaxBuiltIn: "#31748f",
  syntaxType: "#9ccfd8",
  syntaxLiteral: "#f6c177",
  syntaxNumber: "#f6c177",
  syntaxRegexp: "#ebbcba",
  syntaxString: "#9ccfd8",
  syntaxSubst: "#908caa",
  syntaxSymbol: "#c4a7e7",
  syntaxClass: "#9ccfd8",
  syntaxFunction: "#31748f",
  syntaxTitle: "#c4a7e7",
  syntaxParams: "#908caa",
  syntaxComment: "#6e6a86",
  syntaxTag: "#eb6f92",
  syntaxAttr: "#ebbcba",
  syntaxVariable: "#e0def4",
};

export const THEMES: Record<string, ThemeTokens> = {
  excelsior: EXCELSIOR,
};

export const DEFAULT_THEME_NAME = "excelsior";
